### ISSUE TITLE
insufficient user rights in lolminer?

### ISSUE THREAD

**Issue by Blockvolt** [compscidr/lolminer-docker#30]
Hello,

thank you for your work!

My issue:
lolminer starts and works fine without any special arguments, but when I want to change my overclocking settings I get the following error code:

Applying overclock settings...
GPU 0: core clock offset 100 not applied (insufficient user rights).
GPU 0: locked core clock not applied.
GPU 0: locked memory clock not applied.
GPU 0: power limit 170 not applied.
GPU 0: fan percentage 60 not applied.

How can I solve the problem?

I`m running docker as root.

Tahnk you!

**Comment by compscidr** [comment]
One thing you could try is running the container itself in privileged mode (otherwise I think it restricts the containers abilities even when you are running docker itself as root): https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities

Are you running the nvidia or amd container? I might also need to investigate whether we need a root user on the container itself if that doesn't work.

**Comment by Blockvolt** [comment]
You are my hero!!!
Its working with '--privileged'

I`m running the nvidia container

**Comment by compscidr** [comment]
Great, I'll close the issue then - reopen if you have any other issues!
